version: "4"

services:
  angular:
    build:
      dockerfile: Dockerfile
    container_name: angular_logisticants
    ports:
      - "4200:80"     
    depends_on:
      - maven

  maven:
    build:
      dockerfile: Dockerfile
    container_name: maven_logisticants
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/logisticants
      - SPRING_DATASOURCE_USERNAME=mysql
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db

  db:
    image: mysql:8.1
    container_name: db
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: logisticants

    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

