# Stage 1 : build avec Maven
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2 : Tomcat
FROM tomcat:10.1-jdk17
RUN rm -rf /usr/local/tomcat/webapps/*
# Copier le WAR généré par Maven
COPY --from=build /app/target/logisticants.war /usr/local/tomcat/webapps/app.war
EXPOSE 8080
CMD ["catalina.sh", "run"]


# docker build -f Dockerfile.maven -t logisticants-maven .
# docker run --rm logisticants-maven

# adapter avec le chemin de votre projet sur votre machine
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/app" -w /app maven:3.9.6-eclipse-temurin-17 mvn clean install
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/app" -w /app maven:3.9.6-eclipse-temurin-17 mvn clean test
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/app" -w /app maven:3.9.6-eclipse-temurin-17 mvn clean compile
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/app" -w /app maven:3.9.6-eclipse-temurin-17 mvn clean clean
# docker exec -it logisticants-mysql mysql -u root -p mdp root
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/app" -w /app maven:3.9.6-eclipse-temurin-17 mvn "exec:java" "-Dexec.mainClass=model.TableCreation"


# ranger src/main/java/com/maven/...    

 
