version: "4"

services:
  angular:
    build:
      dockerfile: Dockerfile
    container_name: angular_logisticants
    ports:
      - "4200:80"     
    depends_on:
      - maven

  app:
    build: .
    container_name: logisticants-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/logisticants
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    
  db:
    image: mysql:8.1
    container_name: db
    restart: always
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: logisticants

    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

