services:
  java-app:
    build:
      context: .
      dockerfile: Dockerfile.maven
    container_name: logisticants-java
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/logisticants?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: logisticants
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  angular:
    build:
      context: .
      dockerfile: angular/Dockerfile.angular
    container_name: logisticants-angular
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/app/angular
      - /app/angular/node_modules
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge