FROM node:20-alpine

WORKDIR /app

# Copier uniquement package.json (safe)
COPY package.json ./

# Installer dépendances
RUN npm install -g @angular/cli \
    && npm install

# Copier le reste du projet
COPY . .

EXPOSE 4200

CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200"]

# docker build -f angular/Dockerfile.angular -t logisticants-angular .

# docker run -it --rm logisticants-angular sh (shell)