# Stage 1 : Build avec Maven
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /logisticiants
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests

# Stage 2 : Run avec Java directement
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /logisticiants/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]


# docker build -f .devcontainer/java/Dockerfile.maven -t logisticants-maven . 
# docker logs logisticants-java --tail 100
# docker run --rm logisticants-maven


# adapter avec le chemin de votre projet sur votre machine

# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/logisticiants" -w /logisticiants maven:3.9.6-eclipse-temurin-17 mvn clean install
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/logisticiants" -w /logisticiants maven:3.9.6-eclipse-temurin-17 mvn clean test
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/logisticiants" -w /logisticiants maven:3.9.6-eclipse-temurin-17 mvn clean compile
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/logisticiants" -w /logisticiants maven:3.9.6-eclipse-temurin-17 mvn clean clean
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/logisticiants" -w /logisticiants maven:3.9.6-eclipse-temurin-17 mvn clean package
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/logisticiants" -w /logisticiants maven:3.9.6-eclipse-temurin-17 mvn "exec:java" "-Dexec.mainClass=com.maven.model.TableCreation"
# docker run --rm -it -v "L:\Projet developpements\logisticAnts:/logisticiants" -w /logisticiants maven:3.9.6-eclipse-temurin-17 mvn "exec:java" "-Dexec.mainClass=com.maven.seeder.DatabaseSeeder"


# docker exec -it mysql mysql -u root -p logistants
# ranger src/main/java/com/maven/...    

 
